# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # configure VM
    config.vm.box = "apolloclark/elastic5x-ubuntu14"
    config.vm.box_version = "20170831"

    # configure network ports
    config.vm.network "forwarded_port", host: 9200, guest: 9200 # Elasticsearch
    config.vm.network "forwarded_port", host: 9300, guest: 9300 # Logtash
    config.vm.network "forwarded_port", host: 5601, guest: 5601 # Kibana

    config.vm.provider "virtualbox" do |vb, override|
        vb.cpus = 1
        vb.memory = 4096
        vb.gui = false
    end
end
