# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # configure VM
    config.vm.box = "ubuntu/trusty64"
    
    # configure provisioning
    config.vm.provision "shell", path: "bootstrap.sh"
  
    # configure network ports
    config.vm.network "forwarded_port", host: 9200, guest: 9200 # Elasticsearch
    config.vm.network "forwarded_port", host: 9300, guest: 9300 # Logtash
    config.vm.network "forwarded_port", host: 5601, guest: 5601 # Kibana
  
    config.vm.provider "virtualbox" do |vb, override|
        vb.cpus = 1
        vb.memory = 4096
        vb.gui = false
        vb.name = "vagrant-elk"
        override.vm.synced_folder "./provision", "/vagrant"
 
        # setup local apt-get cache
        # if Vagrant.has_plugin?("vagrant-cachier")
            # Configure cached packages to be shared between instances of the same base box.
            # More info on the "Usage" link above
            # override.cache.scope = :box
        # end
    
        # disable the vbguest update plugin
        if Vagrant.has_plugin?("vagrant-vbguest")
            override.vbguest.auto_update = false
        end
    end
end